services:
  laravel-app:
    image: edgeforge/website:latest
    pull_policy: always
    container_name: website
    ports:
      - "8080:80"  # Maps port 8080 on host to port 80 in the container for nginx
    depends_on:
      - mysql
    networks:
      - laravel-network
#    volumes:            # Enable volume to have persistent container storage. | this will mount local save into container !!! be careful.
#      - ./:/var/www

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: website
    ports:
      - "3306:3306"  # Exposes MySQL on port 3306
    volumes:
      - mysql_data:/var/lib/mysql  # Persistent storage for MySQL data
    networks:
      - laravel-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql  # Connects phpMyAdmin to the MySQL service
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8088:80"  # Maps port 8081 on the host to port 80 in the phpMyAdmin container
    depends_on:
      - mysql
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
